# Generated by Django 5.1.2 on 2024-11-04 12:29

import MMApps.client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_plan_clientaddress_clientmeasurements_clientprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='profile',
            field=models.ImageField(default='default-images/client-default.png', upload_to=MMApps.client.models.profile_image_upload_path),
        ),
    ]
